export default {
    GET_PRODUCT: 'GET_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    FILTER: 'FILTER',
    ADD_INPUT: 'ADD_INPUT',
    CHART_DATE: 'CHART_DATE',
    CHART_WEEK: 'CHART_WEEK',
    CHART_MONTH: 'CHART_MONTH',
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
};
