export default {
    GET_PRODUCT: 'GET_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    FILTER: 'FILTER',
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
};
